version: 0.9.{build}
os: Visual Studio 2017
clone_depth: 2
configuration: Release

pull_requests:
  do_not_increment_build_number: true

init:
  - git config --global core.autocrlf input
  - ps: $env:GIT_HASH=$env:APPVEYOR_REPO_COMMIT.Substring(0, 10)
  - ps: If ("$env:APPVEYOR_REPO_TAG" -ne "true") { $env:VERSION_SUFFIX="pre" }
  - ps: 'Write-Output "Version: $($env:APPVEYOR_BUILD_VERSION)-$($env:VERSION_SUFFIX)"'

before_build:
  - ps: .\build\Set-BuildVersion -Version $env:APPVEYOR_BUILD_VERSION -Suffix $env:VERSION_SUFFIX
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - ps: dotnet build -c Release

test_script:
  - ps: dotnet test .\OAuth2.Tests\OAuth2.Tests.csproj -f netcoreapp2.1

after_test:
  - ps: dotnet pack -c Release

artifacts:
  - path: artifacts\*.nupkg
    name: NuGet
